Description: >
  udacity rds cloud formation script assigment

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

Resources:
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 8
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: rds-test-db
      Engine: MySQL
      EngineVersion: 5.7
      MasterUsername: dami
      MasterUserPassword: password
      MultiAZ: false
      Port: 3306
      PubliclyAccessible: true
      VPCSecurityGroups:
        - sg-0d4b4cd7789664c23
